#!/bin/bash
# Clear the DISPLAY.
# unsetenv DISPLAY
# Call MATLAB with the appropriate input and output,
# make it immune to hangups and quits using ''nohup'',
# and run it in the background.


for n in  200 500 1000 2000 5000 10000  # number of samples
do 
	nohup python -u da_expe.py  -n $n -d 1 > out_dom_toy_$n.log &
done

for n in  200 500 1000 2000 3000 4000   # number of samples
do 
	nohup python -u da_expe.py  -n $n -d 2 > out_dom_mnist_$n.log &	
done


