#!/bin/bash
# Clear the DISPLAY.
# unsetenv DISPLAY
# Call MATLAB with the appropriate input and output,
# make it immune to hangups and quits using ''nohup'',
# and run it in the background.


for n in  200 500 1000 2000 5000 10000  # dimension
do 
	nohup python -u wda_toy.py  -n $n > out_wda_tou_$n.log &
	
done




